package GUI;

import BUS.*;
import DTO.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class DatHang_GUI extends javax.swing.JPanel {

    DefaultTableModel dProduct, dOrder;
    HoaDon_BUS busHD;
    CTHD_BUS busCTHD;
    NhanVien_BUS busNV;
    KhachHang_BUS busKH;
    Ban_BUS busBan;
    SanPham_BUS busSP;
    LoaiSP_BUS busLSP;

    public DatHang_GUI() {
        initComponents();
        setPanel();
    }

    public DatHang_GUI(HoaDon hd) {
        initComponents();
        setPanel();
        setDataOrder(busCTHD.getCTHDbyID(hd.getMaHD()));
    }

    //Hàm khởi tạo
    private void setPanel() {
        //Gọi hàm khởi tạo
        busHD = new HoaDon_BUS();
        busCTHD = new CTHD_BUS();
        busNV = new NhanVien_BUS();
        busKH = new KhachHang_BUS();
        busBan = new Ban_BUS();
        busSP = new SanPham_BUS();
        busLSP = new LoaiSP_BUS();

        //Cấu hình table
        setDProduct();
        setDOrder();

        //Lấy dữ liệu table
        setDataProduct(busSP.getAllSP());

        //Cấu hình các comboBox
        setCBX();
    }

    //Hàm cấu hình table
    private void setDProduct() {
        dProduct = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblProduct.setModel(dProduct);
        dProduct.addColumn("Mã SP");
        dProduct.addColumn("Tên SP");
    }

    private void setDOrder() {
        dOrder = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblOrder.setModel(dOrder);
        String order[] = {"Mã SP", "Tên SP", "Đơn giá", "Số lượng", "Thành tiền"};
        for (String i : order) {
            dOrder.addColumn(i);
        }
    }

    //Hàm lấy dữ liệu cho table
    private void setDataProduct(List<SanPham> sps) {
        dProduct.setRowCount(0);
        for (SanPham i : sps) {
            dProduct.addRow(new Object[]{i.getMaSP(), i.getTenSP()});
        }
    }

    private void setDataOrder(List<CTHD> cts) {
        dOrder.setRowCount(0);
        for (CTHD i : cts) {
            SanPham sp = busSP.getSPbyID(i.getMaSP());
            int money = sp.getDonGia() * i.getSoLuong();
            dOrder.addRow(new Object[]{sp.getMaSP(), sp.getTenSP(), sp.getDonGia(), i.getSoLuong(), money});
        }
    }

    //Hàm cấu hình comboBox
    private void setCBX() {
        //comboBox phân loại
        cbxSort.removeAllItems();
        cbxSort.addItem("All");
        for (LoaiSP i : busLSP.getAllLSP()) {
            cbxSort.addItem(i.getTenLSP());
        }

        //comboBox khách hàng
        cbxKH.removeAllItems();
        for (KhachHang i : busKH.getAllKH()) {
            cbxKH.addItem(i.getMaKH());
        }

        //comboBox nhân viên
        cbxNV.removeAllItems();
        for (NhanVien i : busNV.getAllNV()) {
            cbxNV.addItem(i.getMaNV());
        }

        //comboBox bàn
        cbxBan.removeAllItems();
        for (Ban i : busBan.getAllBan()) {
            cbxBan.addItem(i.getMaBan());
        }

        //comboBox thời gian
        cbxHour.removeAllItems();
        for (int i = 8; i < 22; i++) {
            cbxHour.addItem(String.valueOf(i));
        }

        cbxMinute.removeAllItems();
        for (int i = 0; i < 61; i += 5) {
            cbxMinute.addItem(String.valueOf(i));
        }
    }

    //Hàm chỉnh textfield
    private void setChange(boolean b) {
        txtSP.setEditable(b);
        txtName.setEditable(b);
        txtPrice.setEditable(b);
    }

    //Hàm reset
    private void Reset() {
        txtSP.setText("");
        txtName.setText("");
        txtPrice.setText("");
        txtQuantity.setText("");
        setChange(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProduct = new javax.swing.JPanel();
        pnlSort = new javax.swing.JPanel();
        pnlCBXSort = new javax.swing.JPanel();
        cbxSort = new javax.swing.JComboBox<>();
        pnlSearch = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSEARCH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        pnlDetails = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlDetail = new javax.swing.JPanel();
        pnlReceipt = new javax.swing.JPanel();
        pnlReceiptTitle = new javax.swing.JPanel();
        lblHD = new javax.swing.JLabel();
        lblKH = new javax.swing.JLabel();
        lblNV = new javax.swing.JLabel();
        lblBan = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        pnlReceiptText = new javax.swing.JPanel();
        txtHD = new javax.swing.JTextField();
        cbxKH = new javax.swing.JComboBox<>();
        cbxNV = new javax.swing.JComboBox<>();
        cbxBan = new javax.swing.JComboBox<>();
        pnlTime = new javax.swing.JPanel();
        cbxHour = new javax.swing.JComboBox<>();
        cbxMinute = new javax.swing.JComboBox<>();
        pnlOrder = new javax.swing.JPanel();
        pnlOrderTitle = new javax.swing.JPanel();
        lblSP = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        pnlOrderText = new javax.swing.JPanel();
        txtSP = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        pnlBTN = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        pnlOrderTBL = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        pnlTotal = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlProduct.setLayout(new java.awt.BorderLayout());

        pnlSort.setBackground(new java.awt.Color(255, 255, 255));

        pnlCBXSort.setBackground(new java.awt.Color(255, 255, 255));
        pnlCBXSort.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phân loại", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(159, 32, 66))); // NOI18N
        pnlCBXSort.setLayout(new java.awt.GridLayout());

        cbxSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSortActionPerformed(evt);
            }
        });
        pnlCBXSort.add(cbxSort);

        pnlSearch.setBackground(new java.awt.Color(255, 255, 255));
        pnlSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(159, 32, 66))); // NOI18N
        pnlSearch.setLayout(new java.awt.BorderLayout());
        pnlSearch.add(txtSearch, java.awt.BorderLayout.CENTER);

        btnSEARCH.setBackground(new java.awt.Color(159, 32, 66));
        btnSEARCH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSEARCH.setForeground(new java.awt.Color(255, 255, 255));
        btnSEARCH.setText("Tìm");
        pnlSearch.add(btnSEARCH, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout pnlSortLayout = new javax.swing.GroupLayout(pnlSort);
        pnlSort.setLayout(pnlSortLayout);
        pnlSortLayout.setHorizontalGroup(
            pnlSortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCBXSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSortLayout.setVerticalGroup(
            pnlSortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSortLayout.createSequentialGroup()
                .addComponent(pnlCBXSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlProduct.add(pnlSort, java.awt.BorderLayout.PAGE_START);

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tblProduct.setRowHeight(30);
        tblProduct.getTableHeader().setReorderingAllowed(false);
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        pnlProduct.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetails.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(159, 32, 66));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ĐẶT HÀNG");
        pnlDetails.add(lblTitle, java.awt.BorderLayout.PAGE_START);

        pnlDetail.setBackground(new java.awt.Color(255, 255, 255));

        pnlReceipt.setBackground(new java.awt.Color(255, 255, 255));
        pnlReceipt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(159, 32, 66))); // NOI18N

        pnlReceiptTitle.setBackground(new java.awt.Color(255, 255, 255));
        pnlReceiptTitle.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        lblHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHD.setForeground(new java.awt.Color(159, 32, 66));
        lblHD.setText("Mã HĐ");
        pnlReceiptTitle.add(lblHD);

        lblKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKH.setForeground(new java.awt.Color(159, 32, 66));
        lblKH.setText("Mã KH");
        pnlReceiptTitle.add(lblKH);

        lblNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNV.setForeground(new java.awt.Color(159, 32, 66));
        lblNV.setText("Mã NV");
        pnlReceiptTitle.add(lblNV);

        lblBan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBan.setForeground(new java.awt.Color(159, 32, 66));
        lblBan.setText("Mã bàn");
        pnlReceiptTitle.add(lblBan);

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(159, 32, 66));
        lblTime.setText("Thời gian");
        pnlReceiptTitle.add(lblTime);

        pnlReceiptText.setBackground(new java.awt.Color(255, 255, 255));
        pnlReceiptText.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        txtHD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pnlReceiptText.add(txtHD);

        cbxKH.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbxKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlReceiptText.add(cbxKH);

        cbxNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbxNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlReceiptText.add(cbxNV);

        cbxBan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbxBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlReceiptText.add(cbxBan);

        pnlTime.setBackground(new java.awt.Color(255, 255, 255));
        pnlTime.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        cbxHour.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbxHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlTime.add(cbxHour);

        cbxMinute.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbxMinute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlTime.add(cbxMinute);

        pnlReceiptText.add(pnlTime);

        javax.swing.GroupLayout pnlReceiptLayout = new javax.swing.GroupLayout(pnlReceipt);
        pnlReceipt.setLayout(pnlReceiptLayout);
        pnlReceiptLayout.setHorizontalGroup(
            pnlReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReceiptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlReceiptTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlReceiptText, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlReceiptLayout.setVerticalGroup(
            pnlReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReceiptLayout.createSequentialGroup()
                .addGroup(pnlReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlReceiptTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlReceiptText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlOrder.setBackground(new java.awt.Color(255, 255, 255));
        pnlOrder.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(159, 32, 66))); // NOI18N

        pnlOrderTitle.setBackground(new java.awt.Color(255, 255, 255));
        pnlOrderTitle.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        lblSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSP.setForeground(new java.awt.Color(159, 32, 66));
        lblSP.setText("Mã SP");
        pnlOrderTitle.add(lblSP);

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(159, 32, 66));
        lblName.setText("Tên SP");
        pnlOrderTitle.add(lblName);

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(159, 32, 66));
        lblPrice.setText("Đơn giá");
        pnlOrderTitle.add(lblPrice);

        lblQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(159, 32, 66));
        lblQuantity.setText("Số lượng");
        pnlOrderTitle.add(lblQuantity);

        pnlOrderText.setBackground(new java.awt.Color(255, 255, 255));
        pnlOrderText.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        txtSP.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pnlOrderText.add(txtSP);

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pnlOrderText.add(txtName);

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pnlOrderText.add(txtPrice);

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pnlOrderText.add(txtQuantity);

        javax.swing.GroupLayout pnlOrderLayout = new javax.swing.GroupLayout(pnlOrder);
        pnlOrder.setLayout(pnlOrderLayout);
        pnlOrderLayout.setHorizontalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOrderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlOrderText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlOrderLayout.setVerticalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOrderTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlOrderText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlDetailLayout = new javax.swing.GroupLayout(pnlDetail);
        pnlDetail.setLayout(pnlDetailLayout);
        pnlDetailLayout.setHorizontalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDetailLayout.setVerticalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailLayout.createSequentialGroup()
                .addComponent(pnlReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlDetails.add(pnlDetail, java.awt.BorderLayout.CENTER);

        pnlBTN.setBackground(new java.awt.Color(255, 255, 255));
        pnlBTN.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(159, 32, 66))); // NOI18N
        pnlBTN.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        jButton1.setBackground(new java.awt.Color(159, 32, 66));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm");
        pnlBTN.add(jButton1);

        jButton2.setBackground(new java.awt.Color(159, 32, 66));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sửa");
        pnlBTN.add(jButton2);

        jButton3.setBackground(new java.awt.Color(159, 32, 66));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Xóa");
        pnlBTN.add(jButton3);

        jButton4.setBackground(new java.awt.Color(159, 32, 66));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Đặt lại");
        pnlBTN.add(jButton4);

        jButton5.setBackground(new java.awt.Color(159, 32, 66));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Xác nhận");
        pnlBTN.add(jButton5);

        jButton6.setBackground(new java.awt.Color(159, 32, 66));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Hủy");
        pnlBTN.add(jButton6);

        pnlDetails.add(pnlBTN, java.awt.BorderLayout.PAGE_END);

        pnlOrderTBL.setBackground(new java.awt.Color(255, 255, 255));
        pnlOrderTBL.setLayout(new java.awt.BorderLayout());

        tblOrder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOrder.setRowHeight(30);
        tblOrder.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblOrder);

        pnlOrderTBL.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnlTotal.setBackground(new java.awt.Color(255, 255, 255));
        pnlTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tổng tiền", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(159, 32, 66))); // NOI18N
        pnlTotal.setLayout(new java.awt.GridLayout());

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(159, 32, 66));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("0");
        pnlTotal.add(lblTotal);

        pnlOrderTBL.add(pnlTotal, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlOrderTBL, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOrderTBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnlDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSortActionPerformed
        String sort = String.valueOf(cbxSort.getSelectedIndex());
        if (sort.equals("0")) {
            setDataProduct(busSP.getAllSP());
        } else {
            setDataProduct(busSP.searchSP(sort, 3));
        }
    }//GEN-LAST:event_cbxSortActionPerformed

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        int row = tblProduct.getSelectedRow();
        if(row != -1){
            SanPham sp = busSP.getSPbyID(String.valueOf(dProduct.getValueAt(row, 0)));
            txtSP.setText(sp.getMaSP());
            txtName.setText(sp.getTenSP());
            txtPrice.setText(String.valueOf(sp.getDonGia()));
            setChange(false);
        }
    }//GEN-LAST:event_tblProductMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSEARCH;
    private javax.swing.JComboBox<String> cbxBan;
    private javax.swing.JComboBox<String> cbxHour;
    private javax.swing.JComboBox<String> cbxKH;
    private javax.swing.JComboBox<String> cbxMinute;
    private javax.swing.JComboBox<String> cbxNV;
    private javax.swing.JComboBox<String> cbxSort;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBan;
    private javax.swing.JLabel lblHD;
    private javax.swing.JLabel lblKH;
    private javax.swing.JLabel lblNV;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSP;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlBTN;
    private javax.swing.JPanel pnlCBXSort;
    private javax.swing.JPanel pnlDetail;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlOrder;
    private javax.swing.JPanel pnlOrderTBL;
    private javax.swing.JPanel pnlOrderText;
    private javax.swing.JPanel pnlOrderTitle;
    private javax.swing.JPanel pnlProduct;
    private javax.swing.JPanel pnlReceipt;
    private javax.swing.JPanel pnlReceiptText;
    private javax.swing.JPanel pnlReceiptTitle;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JPanel pnlSort;
    private javax.swing.JPanel pnlTime;
    private javax.swing.JPanel pnlTotal;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtHD;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSP;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
