package GUI;

import BUS.NhanVien_BUS;
import DTO.NhanVien;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class NhanVien_GUI extends javax.swing.JPanel {

    DefaultTableModel dt;
    NhanVien_BUS busNV;
    NhanVien nv;

    public NhanVien_GUI() {
        initComponents();
        busNV = new NhanVien_BUS();
        nv = new NhanVien();
        dt = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        Table.setModel(dt);

        cbxSearch.setEditable(false);
        cbxSearch.removeAllItems();

        String cbx[] = {"Mã nhân viên", "Họ tên", "Giới tính", "Số điện thoại", "Email", "Địa chỉ"};
        for (String s : cbx) {
            cbxSearch.addItem(s);
            dt.addColumn(s);
        }
        
        setTableData(busNV.getAllNV());
    }

    private void setTableData(List<NhanVien> nvs) {
        for (NhanVien nv : nvs) {
            String gioiTinh = nv.getGioiTinh() == 0 ? "Nữ" : "Nam";
            dt.addRow(new Object[]{nv.getMaNV(), nv.getHoTen(), gioiTinh, nv.getSdt(), nv.getEmail(), nv.getDiaChi()});
        }
    }

    private void setTableData2(List<NhanVien> nvs) {
        dt.setRowCount(0);
        setTableData(nvs);
        Reset();
    }

    private void check() throws Exception {
        String regID = "NV\\d{3}",
                regName = ".*\\d+.*",
                regPhone = "\\d{10}",
                regEmail = "^(\\w){3,}(@gmail\\.com)$";

        if (txtName.getText().trim().isEmpty()) {
            throw new Exception("Họ tên trống");
        } else if (txtPhone.getText().trim().isEmpty()) {
            throw new Exception("Số điện thoại trống");
        } else if (txtEmail.getText().trim().isEmpty()) {
            throw new Exception("Email trống");
        } else if (txtAddress.getText().trim().isEmpty()) {
            throw new Exception("Địa chỉ trống");
        } else if (!txtID.getText().trim().matches(regID)) {
            throw new Exception("Mã không đúng định đạng");
        } else if (txtName.getText().trim().matches(regName)) {
            throw new Exception("Họ tên không đúng");
        } else if (!txtPhone.getText().trim().matches(regPhone)) {
            throw new Exception("Số điện thoại không đúng");
        } else if (!txtEmail.getText().trim().matches(regEmail)) {
            throw new Exception("Email không đúng");
        }
    }
    
    private void Reset() {
        txtID.setText("");
        txtID.setEnabled(true);
        txtName.setText("");
        rdoM.setSelected(true);
        txtPhone.setText("");
        txtEmail.setText("");
        txtAddress.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup_Sex = new javax.swing.ButtonGroup();
        contentPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlDetails = new javax.swing.JPanel();
        pnlDetail = new javax.swing.JPanel();
        pnlID = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        pnlName = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        pnlSex = new javax.swing.JPanel();
        rdoM = new javax.swing.JRadioButton();
        rdoF = new javax.swing.JRadioButton();
        lblSex = new javax.swing.JLabel();
        pnlPhone = new javax.swing.JPanel();
        txtPhone = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        pnlEmail = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        pnlAddress = new javax.swing.JPanel();
        txtAddress = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        pnlSEARCH = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSEARCH = new javax.swing.JButton();
        cbxSearch = new javax.swing.JComboBox<>();
        lblSearchType = new javax.swing.JLabel();
        pnlBTN = new javax.swing.JPanel();
        btnADD = new javax.swing.JButton();
        btnUP = new javax.swing.JButton();
        btnDEL = new javax.swing.JButton();
        btnREF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setMaximumSize(new java.awt.Dimension(400, 32767));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(159, 32, 66));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("NHÂN VIÊN");

        pnlDetails.setBackground(new java.awt.Color(255, 255, 255));

        pnlDetail.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(159, 32, 66))); // NOI18N

        pnlID.setBackground(new java.awt.Color(248, 229, 238));

        lblID.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblID.setForeground(new java.awt.Color(159, 32, 66));
        lblID.setText("Mã NV");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlIDLayout = new javax.swing.GroupLayout(pnlID);
        pnlID.setLayout(pnlIDLayout);
        pnlIDLayout.setHorizontalGroup(
            pnlIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID)
                .addContainerGap())
        );
        pnlIDLayout.setVerticalGroup(
            pnlIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlIDLayout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pnlName.setBackground(new java.awt.Color(248, 229, 238));
        pnlName.setPreferredSize(new java.awt.Dimension(167, 44));

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(159, 32, 66));
        lblName.setText("Họ tên");

        javax.swing.GroupLayout pnlNameLayout = new javax.swing.GroupLayout(pnlName);
        pnlName.setLayout(pnlNameLayout);
        pnlNameLayout.setHorizontalGroup(
            pnlNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName)
                .addContainerGap())
        );
        pnlNameLayout.setVerticalGroup(
            pnlNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlSex.setBackground(new java.awt.Color(248, 229, 238));
        pnlSex.setPreferredSize(new java.awt.Dimension(167, 44));

        btnGroup_Sex.add(rdoM);
        rdoM.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rdoM.setForeground(new java.awt.Color(159, 32, 66));
        rdoM.setText("Nam");

        btnGroup_Sex.add(rdoF);
        rdoF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rdoF.setForeground(new java.awt.Color(159, 32, 66));
        rdoF.setText("Nữ");

        lblSex.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSex.setForeground(new java.awt.Color(159, 32, 66));
        lblSex.setText("Giới tính");

        javax.swing.GroupLayout pnlSexLayout = new javax.swing.GroupLayout(pnlSex);
        pnlSex.setLayout(pnlSexLayout);
        pnlSexLayout.setHorizontalGroup(
            pnlSexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSex, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSexLayout.setVerticalGroup(
            pnlSexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSexLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSexLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblSex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(rdoM, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(rdoF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlPhone.setBackground(new java.awt.Color(248, 229, 238));
        pnlPhone.setPreferredSize(new java.awt.Dimension(167, 44));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(159, 32, 66));
        lblPhone.setText("SĐT");

        javax.swing.GroupLayout pnlPhoneLayout = new javax.swing.GroupLayout(pnlPhone);
        pnlPhone.setLayout(pnlPhoneLayout);
        pnlPhoneLayout.setHorizontalGroup(
            pnlPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhone)
                .addContainerGap())
        );
        pnlPhoneLayout.setVerticalGroup(
            pnlPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPhoneLayout.createSequentialGroup()
                        .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pnlEmail.setBackground(new java.awt.Color(248, 229, 238));
        pnlEmail.setPreferredSize(new java.awt.Dimension(167, 44));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(159, 32, 66));
        lblEmail.setText("Email");

        javax.swing.GroupLayout pnlEmailLayout = new javax.swing.GroupLayout(pnlEmail);
        pnlEmail.setLayout(pnlEmailLayout);
        pnlEmailLayout.setHorizontalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail)
                .addContainerGap())
        );
        pnlEmailLayout.setVerticalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlAddress.setBackground(new java.awt.Color(248, 229, 238));
        pnlAddress.setPreferredSize(new java.awt.Dimension(167, 44));

        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(159, 32, 66));
        lblAddress.setText("Địa chỉ");

        javax.swing.GroupLayout pnlAddressLayout = new javax.swing.GroupLayout(pnlAddress);
        pnlAddress.setLayout(pnlAddressLayout);
        pnlAddressLayout.setHorizontalGroup(
            pnlAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress)
                .addContainerGap())
        );
        pnlAddressLayout.setVerticalGroup(
            pnlAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlDetailLayout = new javax.swing.GroupLayout(pnlDetail);
        pnlDetail.setLayout(pnlDetailLayout);
        pnlDetailLayout.setHorizontalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
            .addComponent(pnlSex, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
            .addComponent(pnlName, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
            .addComponent(pnlID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
            .addComponent(pnlAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        pnlDetailLayout.setVerticalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailLayout.createSequentialGroup()
                .addComponent(pnlID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblSearch.setText("Tìm kiếm");

        btnSEARCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnSEARCH.setToolTipText("Tìm kiếm");
        btnSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEARCHActionPerformed(evt);
            }
        });

        cbxSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSearchType.setText("Loại");

        javax.swing.GroupLayout pnlSEARCHLayout = new javax.swing.GroupLayout(pnlSEARCH);
        pnlSEARCH.setLayout(pnlSEARCHLayout);
        pnlSEARCHLayout.setHorizontalGroup(
            pnlSEARCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSEARCHLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlSEARCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSearch)
                    .addComponent(lblSearchType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSEARCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxSearch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSEARCHLayout.setVerticalGroup(
            pnlSEARCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSEARCHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSEARCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSEARCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSEARCHLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlSEARCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlSEARCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlDetailsLayout = new javax.swing.GroupLayout(pnlDetails);
        pnlDetails.setLayout(pnlDetailsLayout);
        pnlDetailsLayout.setHorizontalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSEARCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDetailsLayout.setVerticalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailsLayout.createSequentialGroup()
                .addComponent(pnlDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(113, 113, 113)
                .addComponent(pnlSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlBTN.setBackground(new java.awt.Color(255, 255, 255));
        pnlBTN.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btnADD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnADD.setToolTipText("Thêm nhân viên");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });
        pnlBTN.add(btnADD);

        btnUP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow_circle_up.png"))); // NOI18N
        btnUP.setToolTipText("Sửa nhân viên");
        btnUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPActionPerformed(evt);
            }
        });
        pnlBTN.add(btnUP);

        btnDEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel.png"))); // NOI18N
        btnDEL.setToolTipText("Xóa nhân viên");
        btnDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELActionPerformed(evt);
            }
        });
        pnlBTN.add(btnDEL);

        btnREF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnREF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnREF.setToolTipText("Đặt lại và cập nhật");
        btnREF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREFActionPerformed(evt);
            }
        });
        pnlBTN.add(btnREF);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.setRowHeight(30);
        Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEARCHActionPerformed
        if (txtSearch.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Không được bỏ trống", "Thông báo", JOptionPane.ERROR_MESSAGE);
        else {
            String s = txtSearch.getText();
            int t = cbxSearch.getSelectedIndex();
            if (t == 2) {
                if (s.matches("Nam|nam|1")) {
                    setTableData2(busNV.searchNV("1", 2));
                } else if (s.matches("Nữ|nữ|nu|Nu|0")) {
                    setTableData2(busNV.searchNV("0", 2));
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm được nhân viên", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            } else if (busNV.searchNV(s, t).isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm được nhân viên", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                setTableData2(busNV.searchNV(s, t));
            }
        }
    }//GEN-LAST:event_btnSEARCHActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        try {
            check();
            String id = txtID.getText().trim();

            if (busNV.getNVbyID(id) != null) {
                JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                nv = new NhanVien();
                nv.setMaNV(txtID.getText());
                nv.setHoTen(txtName.getText());
                int gioiTinh = rdoM.isSelected() ? 1 : 0;
                nv.setGioiTinh(gioiTinh);
                nv.setSdt(txtPhone.getText().trim());
                nv.setEmail(txtEmail.getText().trim());
                nv.setDiaChi(txtAddress.getText().trim());

                busNV.addNV(nv);
                JOptionPane.showMessageDialog(this, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                setTableData2(busNV.getAllNV());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnADDActionPerformed

    private void btnUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPActionPerformed
        int row = Table.getSelectedRow();
        if (row == -1)
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên", "Thông báo", JOptionPane.ERROR_MESSAGE);
        else {
            try {
                check();

                nv = new NhanVien();
                nv.setMaNV(String.valueOf(Table.getValueAt(row, 0)));
                nv.setHoTen(txtName.getText());
                int gioiTinh = rdoM.isSelected() ? 1 : 0;
                nv.setGioiTinh(gioiTinh);
                nv.setSdt(txtPhone.getText().trim());
                nv.setEmail(txtEmail.getText().trim());
                nv.setDiaChi(txtAddress.getText().trim());

                //Thực hiện truy vấn database
                busNV.updateNV(nv);

                //Xuất thông báo
                JOptionPane.showMessageDialog(this, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                //Cập nhật bảng
                setTableData2(busNV.getAllNV());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUPActionPerformed

    private void btnDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELActionPerformed
        int row = Table.getSelectedRow();
        if (row == -1)
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên", "Thông báo", JOptionPane.ERROR_MESSAGE);
        else {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?");

            if (confirm == JOptionPane.YES_OPTION) {
                String id = String.valueOf(Table.getValueAt(row, 0));
                busNV.deleteNV(id);
                JOptionPane.showMessageDialog(this, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                setTableData2(busNV.getAllNV());
            }
        }
    }//GEN-LAST:event_btnDELActionPerformed

    private void btnREFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREFActionPerformed
        setTableData2(busNV.getAllNV());
    }//GEN-LAST:event_btnREFActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        int row = Table.getSelectedRow();

        if (row != -1) {
            txtID.setText(String.valueOf(Table.getValueAt(row, 0)));
            txtName.setText(String.valueOf(Table.getValueAt(row, 1)));
            if (String.valueOf(Table.getValueAt(row, 2)).equals("Nam")) {
                rdoM.setSelected(true);
            } else {
                rdoF.setSelected(true);
            }
            txtID.setEnabled(false);
            txtPhone.setText(String.valueOf(Table.getValueAt(row, 3)));
            txtEmail.setText(String.valueOf(Table.getValueAt(row, 4)));
            txtAddress.setText(String.valueOf(Table.getValueAt(row, 5)));
        }
    }//GEN-LAST:event_TableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDEL;
    private javax.swing.ButtonGroup btnGroup_Sex;
    private javax.swing.JButton btnREF;
    private javax.swing.JButton btnSEARCH;
    private javax.swing.JButton btnUP;
    private javax.swing.JComboBox<String> cbxSearch;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSearchType;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlAddress;
    private javax.swing.JPanel pnlBTN;
    private javax.swing.JPanel pnlDetail;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlEmail;
    private javax.swing.JPanel pnlID;
    private javax.swing.JPanel pnlName;
    private javax.swing.JPanel pnlPhone;
    private javax.swing.JPanel pnlSEARCH;
    private javax.swing.JPanel pnlSex;
    private javax.swing.JRadioButton rdoF;
    private javax.swing.JRadioButton rdoM;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
