package GUI;
public class pnlTest extends javax.swing.JPanel {
    public pnlTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBTN = new javax.swing.JPanel();
        btnKH = new javax.swing.JButton();
        btnNV = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout(0, 5));

        pnlBTN.setBackground(new java.awt.Color(255, 255, 255));
        pnlBTN.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btnKH.setBackground(new java.awt.Color(159, 32, 66));
        btnKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKH.setForeground(new java.awt.Color(255, 255, 255));
        btnKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/person.png"))); // NOI18N
        btnKH.setText("Khách hàng");
        btnKH.setIconTextGap(6);
        btnKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHActionPerformed(evt);
            }
        });
        pnlBTN.add(btnKH);

        btnNV.setBackground(new java.awt.Color(159, 32, 66));
        btnNV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNV.setForeground(new java.awt.Color(255, 255, 255));
        btnNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/staff.png"))); // NOI18N
        btnNV.setText("Nhân viên");
        btnNV.setIconTextGap(6);
        btnNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVActionPerformed(evt);
            }
        });
        pnlBTN.add(btnNV);

        add(pnlBTN, java.awt.BorderLayout.PAGE_START);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(159, 32, 66));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        pnlContent.add(jPanel3, "card2");

        add(pnlContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHActionPerformed
        pnlContent.removeAll();
        pnlContent.repaint();
        pnlContent.revalidate();
        
        pnlContent.add(new KhachHang_GUI());
        pnlContent.repaint();
        pnlContent.revalidate();
    }//GEN-LAST:event_btnKHActionPerformed

    private void btnNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNVActionPerformed
        pnlContent.removeAll();
        pnlContent.repaint();
        pnlContent.revalidate();
        
        pnlContent.add(new NhanVien_GUI());
        pnlContent.repaint();
        pnlContent.revalidate();
    }//GEN-LAST:event_btnNVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKH;
    private javax.swing.JButton btnNV;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnlBTN;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
