/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.LoaiSP_BUS;
import BUS.SanPham_BUS;
import DTO.LoaiSP;
import DTO.SanPham;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SanPham_GUI extends javax.swing.JPanel {

    SanPham_BUS busSP;
    LoaiSP_BUS busLSP;
    DefaultTableModel dt;
    SanPham sp;

    public SanPham_GUI() {
        initComponents();
        busLSP = new LoaiSP_BUS();
        busSP = new SanPham_BUS();
        sp = new SanPham();
        dt = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        Table.setModel(dt);
        dt.addColumn("Mã sản phẩm");
        dt.addColumn("Tên sản phẩm");
        dt.addColumn("Đơn giá");
        dt.addColumn("Loại sản phẩm");

        setTableData(busSP.getAllSP());

        //Logic ComboBox LoaiSP
        cbxTypeProduct.setEditable(false);
        cbxTypeProduct.removeAllItems();

        for (LoaiSP l : busLSP.getAllLSP()) {
            cbxTypeProduct.addItem(l.getTenLSP());
        }

        //Logic ComboBox Tim kiem
        cbxSearch.setEditable(false);
        cbxSearch.removeAllItems();

        String cbx[] = {"Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Loại sản phẩm"};
        for (String s : cbx) {
            cbxSearch.addItem(s);
        };
    }

    private void setTableData(List<SanPham> sps) {
        for (SanPham sp : sps) {
            for (LoaiSP i : busLSP.getAllLSP()) {
                if (sp.getMaLSP().equals(i.getMaLSP())) {
                    dt.addRow(new Object[]{sp.getMaSP(), sp.getTenSP(), sp.getDonGia(), i.getTenLSP()});
                    break;
                }
            }
        }
    }

    private void setTableData2(List<SanPham> sps) {
        dt.setRowCount(0);
        setTableData(sps);
        Reset();
    }

    private void Reset() {
        txtID.setText("");
        txtID.setEnabled(true);
        txtName.setText("");
        txtPrice.setText("");
        cbxTypeProduct.setSelectedIndex(0);
    }

    private boolean checkEmpty() {
        return txtID.getText().trim().isEmpty()
                || txtName.getText().trim().isEmpty()
                || txtPrice.getText().trim().isEmpty();
    }

    private boolean checkID() {
        return txtID.getText().trim().matches("SP\\d{3}");
    }

    private boolean checkName() {
        return txtName.getText().trim().matches("\\D{3,}");
    }

    private boolean checkPrice() {
        return txtPrice.getText().trim().matches("\\d{4,}");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlDetail = new javax.swing.JPanel();
        pnlINFO = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblTypeProduct = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        cbxTypeProduct = new javax.swing.JComboBox<>();
        pnlSEARCH = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSEARCH = new javax.swing.JButton();
        cbxSearch = new javax.swing.JComboBox<>();
        lblSearchType = new javax.swing.JLabel();
        pnlBTN = new javax.swing.JPanel();
        btnADD = new javax.swing.JButton();
        btnUP = new javax.swing.JButton();
        btnDEL = new javax.swing.JButton();
        btnREF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));

        contentPanel.setBackground(new java.awt.Color(0, 0, 0));
        contentPanel.setForeground(new java.awt.Color(255, 255, 255));
        contentPanel.setMaximumSize(new java.awt.Dimension(400, 32767));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("SẢN PHẨM");

        pnlDetail.setBackground(new java.awt.Color(0, 51, 153));

        pnlINFO.setBackground(pnlDetail.getBackground());
        pnlINFO.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlINFO.setForeground(new java.awt.Color(255, 255, 255));

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("Mã sản phẩm");

        lblTypeProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTypeProduct.setForeground(new java.awt.Color(255, 255, 255));
        lblTypeProduct.setText("Loại SP");
        lblTypeProduct.setToolTipText("Loại sản phẩm");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Tên sản phẩm");

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblPrice.setText("Đơn giá");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cbxTypeProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxTypeProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlINFOLayout = new javax.swing.GroupLayout(pnlINFO);
        pnlINFO.setLayout(pnlINFOLayout);
        pnlINFOLayout.setHorizontalGroup(
            pnlINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlINFOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID)
                    .addComponent(lblTypeProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID)
                    .addComponent(txtName)
                    .addComponent(txtPrice)
                    .addComponent(cbxTypeProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlINFOLayout.setVerticalGroup(
            pnlINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlINFOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTypeProduct)
                    .addComponent(cbxTypeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlSEARCH.setBackground(new java.awt.Color(0, 51, 153));
        pnlSEARCH.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lblSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblSearch.setText("Tìm kiếm");

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnSEARCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnSEARCH.setToolTipText("Tìm kiếm");
        btnSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEARCHActionPerformed(evt);
            }
        });

        cbxSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSearchType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSearchType.setForeground(new java.awt.Color(255, 255, 255));
        lblSearchType.setText("Loại");

        javax.swing.GroupLayout pnlSEARCHLayout = new javax.swing.GroupLayout(pnlSEARCH);
        pnlSEARCH.setLayout(pnlSEARCHLayout);
        pnlSEARCHLayout.setHorizontalGroup(
            pnlSEARCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSEARCHLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlSEARCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSearchType, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSEARCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxSearch, 0, 239, Short.MAX_VALUE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSEARCHLayout.setVerticalGroup(
            pnlSEARCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSEARCHLayout.createSequentialGroup()
                .addGroup(pnlSEARCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSEARCHLayout.createSequentialGroup()
                        .addGroup(pnlSEARCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlSEARCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSEARCH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlDetailLayout = new javax.swing.GroupLayout(pnlDetail);
        pnlDetail.setLayout(pnlDetailLayout);
        pnlDetailLayout.setHorizontalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlINFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlSEARCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDetailLayout.setVerticalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlINFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetailLayout.createSequentialGroup()
                    .addGap(0, 310, Short.MAX_VALUE)
                    .addComponent(pnlSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlBTN.setBackground(new java.awt.Color(0, 0, 0));
        pnlBTN.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btnADD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnADD.setToolTipText("Thêm sản phẩm");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });
        pnlBTN.add(btnADD);

        btnUP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow_circle_up.png"))); // NOI18N
        btnUP.setToolTipText("Sửa sản phẩm");
        btnUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPActionPerformed(evt);
            }
        });
        pnlBTN.add(btnUP);

        btnDEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel.png"))); // NOI18N
        btnDEL.setToolTipText("Xóa sản phẩm");
        btnDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELActionPerformed(evt);
            }
        });
        pnlBTN.add(btnDEL);

        btnREF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnREF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnREF.setToolTipText("Đặt lại và cập nhật");
        btnREF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREFActionPerformed(evt);
            }
        });
        pnlBTN.add(btnREF);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.setRowHeight(30);
        Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEARCHActionPerformed
        if (txtSearch.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Không được bỏ trống", "Thông báo", JOptionPane.ERROR_MESSAGE);
        else {
            String s = txtSearch.getText();
            int t = cbxSearch.getSelectedIndex();
            if (busSP.searchSP(s, t).isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm được sản phẩm", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                setTableData2(busSP.searchSP(s, t));
            }
        }
    }//GEN-LAST:event_btnSEARCHActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        if (checkEmpty())
            JOptionPane.showMessageDialog(this, "Vui lòng nhập dữ liệu", "Thông báo", JOptionPane.ERROR_MESSAGE);
        else if (!checkID())
            JOptionPane.showMessageDialog(this, "Sai mã sản phẩm", "Thông báo", JOptionPane.ERROR_MESSAGE);
        else if (!checkName() || !checkPrice()) {
            if (!checkName()) {
                JOptionPane.showMessageDialog(this, "Sai tên", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else if (!checkPrice()) {
                JOptionPane.showMessageDialog(this, "Sai đơn giá", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            boolean flag = true;
            for (SanPham i : busSP.getAllSP()) {
                if (txtID.getText().equals(i.getMaSP())) {
                    JOptionPane.showMessageDialog(this, "Mã sản phẩm đã tồn tại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    flag = false;
                    break;
                }
            }

            if (flag) {
                sp = new SanPham();
                sp.setMaSP(txtID.getText().trim());
                sp.setTenSP(txtName.getText().trim());
                sp.setDonGia(Integer.parseInt(txtPrice.getText().trim()));

                for (LoaiSP i : busLSP.getAllLSP()) {
                    String s = String.valueOf(cbxTypeProduct.getSelectedItem());
                    if (i.getTenLSP().equals(s)) {
                        sp.setMaLSP(i.getMaLSP());
                        break;
                    }
                }

                busSP.addSP(sp);
                JOptionPane.showMessageDialog(this, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                setTableData2(busSP.getAllSP());
            }
        }
    }//GEN-LAST:event_btnADDActionPerformed

    private void btnUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPActionPerformed
        int row = Table.getSelectedRow();
        if (row == -1)
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm", "Thông báo", JOptionPane.ERROR_MESSAGE);
        else {
            if (checkEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập dữ liệu", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else if (!checkName() || !checkPrice()) {
                if (!checkName()) {
                    JOptionPane.showMessageDialog(this, "Sai tên", "Thông báo", JOptionPane.ERROR_MESSAGE);
                } else if (!checkPrice()) {
                    JOptionPane.showMessageDialog(this, "Sai đơn giá", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                SanPham s1 = new SanPham();
                s1.setMaSP(txtID.getText());
                s1.setTenSP(txtName.getText().trim());
                s1.setDonGia(Integer.parseInt(txtPrice.getText().trim()));

                for (LoaiSP i : busLSP.getAllLSP()) {
                    String s = String.valueOf(cbxTypeProduct.getSelectedItem());
                    if (i.getTenLSP().equals(s)) {
                        s1.setMaLSP(i.getMaLSP());
                        break;
                    }
                }

                busSP.updateSP(s1);
                JOptionPane.showMessageDialog(this, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                setTableData2(busSP.getAllSP());
            }
        }
    }//GEN-LAST:event_btnUPActionPerformed

    private void btnDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELActionPerformed
        int row = Table.getSelectedRow();
        if (row == -1)
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm", "Thông báo", JOptionPane.ERROR_MESSAGE);
        else {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn xóa?");

            if (confirm == JOptionPane.YES_OPTION) {
                String id = String.valueOf(Table.getValueAt(row, 0));
                busSP.deleteSP(id);
                JOptionPane.showMessageDialog(this, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                setTableData2(busSP.getAllSP());
            }
        }
    }//GEN-LAST:event_btnDELActionPerformed

    private void btnREFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREFActionPerformed
        setTableData2(busSP.getAllSP());
    }//GEN-LAST:event_btnREFActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        int row = Table.getSelectedRow();

        if (row != -1) {
            txtID.setText(String.valueOf(Table.getValueAt(row, 0)));
            txtName.setText(String.valueOf(Table.getValueAt(row, 1)));
            txtPrice.setText(String.valueOf(dt.getValueAt(row, 2)));

            for (LoaiSP i : busLSP.getAllLSP()) {
                String cbx = String.valueOf(dt.getValueAt(row, 3));
                if (i.getTenLSP().equals(cbx)) {
                    cbxTypeProduct.setSelectedItem(i.getTenLSP());
                    break;
                }
            }

            txtID.setEnabled(false);
        }
    }//GEN-LAST:event_TableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDEL;
    private javax.swing.JButton btnREF;
    private javax.swing.JButton btnSEARCH;
    private javax.swing.JButton btnUP;
    private javax.swing.JComboBox<String> cbxSearch;
    private javax.swing.JComboBox<String> cbxTypeProduct;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSearchType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTypeProduct;
    private javax.swing.JPanel pnlBTN;
    private javax.swing.JPanel pnlDetail;
    private javax.swing.JPanel pnlINFO;
    private javax.swing.JPanel pnlSEARCH;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
