package GUI;

import BUS.LoaiSP_BUS;
import BUS.SanPham_BUS;
import DTO.LoaiSP;
import DTO.SanPham;
import java.awt.Color;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.plaf.TableUI;
import javax.swing.table.DefaultTableModel;

public class SanPham_GUI extends javax.swing.JPanel {

    DefaultTableModel dt;
    SanPham_BUS busSP;
    LoaiSP_BUS busLSP;

    public SanPham_GUI() {
        initComponents();

        busSP = new SanPham_BUS();
        busLSP = new LoaiSP_BUS();

        setTable();
        setTableData(busSP.getAllSP());

        setCBX();
    }

    //Hàm chỉnh tale
    private void setTable() {
        dt = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        Table.setModel(dt);
        String header[] = {"Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Loại sản phẩm"};
        for (String i : header) {
            dt.addColumn(i);
        }
    }

    //Hàm lấy dữ liệu table
    private void setTableData(List<SanPham> sps) {
        dt.setRowCount(0);
        for (SanPham i : sps) {
            dt.addRow(new Object[]{i.getMaSP(), i.getTenSP(), i.getDonGia(), busLSP.getLSPbyID(i.getMaLSP()).getTenLSP()});
        }
    }

    //Hàm chỉnh comboBox
    private void setCBX() {
        //comboBox phân loại và loại sản phẩm
        cbxSort.removeAllItems();
        cbxType.removeAllItems();

        cbxSort.addItem("All");
        for (LoaiSP i : busLSP.getAllLSP()) {
            cbxSort.addItem(i.getTenLSP());
            cbxType.addItem(i.getTenLSP());
        }

        //comboxBox tìm kiếm
        cbxSearch.removeAllItems();
        String search[] = {"Mã SP", "Tên SP", "Đơn giá"};
        for (String i : search) {
            cbxSearch.addItem(i);
        }
    }

    //Hàm reset
    private void Reset() {
        txtID.setText("");
        txtName.setText("");
        txtPrice.setText("");
        cbxType.setSelectedIndex(0);
        txtID.setEditable(true);

        setTableData(busSP.getAllSP());
    }

    //Hàm check lỗi
    private void check() throws Exception {
        if (txtName.getText().trim().isEmpty()) {
            throw new Exception("Tên sản phẩm trống");
        } else if (txtPrice.getText().trim().isEmpty()) {
            throw new Exception("Đơn giá trống");
        } else if (!txtID.getText().trim().matches("^SP\\d{3}$")
                && !txtID.getText().trim().isEmpty()) {
            throw new Exception("Mã sản phẩm không đúng định dạng");
        } else if (!txtName.getText().trim().matches("\\D{5,}")) {
            throw new Exception("Tên sản phẩm phải có hơn 5 ký tự");
        } else if (!txtPrice.getText().trim().matches("\\d+")) {
            throw new Exception("Đơn giá phải là số");
        } else if (busSP.getSPbyID(txtID.getText().trim()) != null && txtID.isEditable()) {
            throw new Exception("Mã sản phẩm đã tồn tại");
        }
    }

    //Hàm tạo sản phẩm
    private SanPham setSP() {
        SanPham sp = new SanPham();
        int id = busSP.getAllSP().size();
        String maSP = txtID.getText().trim();
        if (maSP.isEmpty()) {
            do {
                maSP = id < 10 ? "SP00" : id < 100 ? "SP0" : "SP";
                maSP = maSP + String.valueOf(id);
            } while (busSP.getSPbyID(maSP) != null);
        }
        sp.setMaSP(maSP);
        sp.setTenSP(txtName.getText().trim());
        sp.setDonGia(Integer.parseInt(txtPrice.getText().trim()));
        sp.setMaLSP(cbxType.getSelectedIndex() + 1);
        return sp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDetails = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlDetail = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lnlName = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        pnlText = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        cbxType = new javax.swing.JComboBox<>();
        pnlFunction = new javax.swing.JPanel();
        pnlS = new javax.swing.JPanel();
        pnlSort = new javax.swing.JPanel();
        cbxSort = new javax.swing.JComboBox<>();
        pnlSearch = new javax.swing.JPanel();
        cbxSearch = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        pnlButton = new javax.swing.JPanel();
        btnADD = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        btnDELETE = new javax.swing.JButton();
        btnREFRESH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetails.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(159, 32, 66));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("SẢN PHẨM");
        pnlDetails.add(lblTitle, java.awt.BorderLayout.PAGE_START);

        pnlDetail.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(159, 32, 66))); // NOI18N

        pnlTitle.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitle.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        lblID.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblID.setForeground(new java.awt.Color(159, 32, 66));
        lblID.setText("Mã SP");
        pnlTitle.add(lblID);

        lnlName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lnlName.setForeground(new java.awt.Color(159, 32, 66));
        lnlName.setText("Tên SP");
        pnlTitle.add(lnlName);

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(159, 32, 66));
        lblPrice.setText("Đơn giá");
        pnlTitle.add(lblPrice);

        lblType.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblType.setForeground(new java.awt.Color(159, 32, 66));
        lblType.setText("Loại SP");
        pnlTitle.add(lblType);

        pnlText.setBackground(new java.awt.Color(255, 255, 255));
        pnlText.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlText.add(txtID);

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlText.add(txtName);

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlText.add(txtPrice);

        cbxType.setBackground(new java.awt.Color(159, 32, 66));
        cbxType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbxType.setForeground(new java.awt.Color(255, 255, 255));
        cbxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlText.add(cbxType);

        javax.swing.GroupLayout pnlDetailLayout = new javax.swing.GroupLayout(pnlDetail);
        pnlDetail.setLayout(pnlDetailLayout);
        pnlDetailLayout.setHorizontalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDetailLayout.setVerticalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailLayout.createSequentialGroup()
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlDetails.add(pnlDetail, java.awt.BorderLayout.CENTER);

        pnlFunction.setBackground(new java.awt.Color(255, 255, 255));
        pnlFunction.setLayout(new java.awt.BorderLayout());

        pnlS.setBackground(new java.awt.Color(255, 255, 255));
        pnlS.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        pnlSort.setBackground(new java.awt.Color(255, 255, 255));
        pnlSort.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phân loại", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(159, 32, 66))); // NOI18N
        pnlSort.setLayout(new java.awt.GridLayout(1, 0));

        cbxSort.setBackground(new java.awt.Color(159, 32, 66));
        cbxSort.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cbxSort.setForeground(new java.awt.Color(255, 255, 255));
        cbxSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSortActionPerformed(evt);
            }
        });
        pnlSort.add(cbxSort);

        pnlS.add(pnlSort);

        pnlSearch.setBackground(new java.awt.Color(255, 255, 255));
        pnlSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(159, 32, 66))); // NOI18N
        pnlSearch.setLayout(new java.awt.BorderLayout(2, 0));

        cbxSearch.setBackground(new java.awt.Color(159, 32, 66));
        cbxSearch.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cbxSearch.setForeground(new java.awt.Color(255, 255, 255));
        cbxSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlSearch.add(cbxSearch, java.awt.BorderLayout.WEST);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pnlSearch.add(txtSearch, java.awt.BorderLayout.CENTER);

        btnSearch.setBackground(new java.awt.Color(159, 32, 66));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Tìm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pnlSearch.add(btnSearch, java.awt.BorderLayout.EAST);

        pnlS.add(pnlSearch);

        pnlFunction.add(pnlS, java.awt.BorderLayout.PAGE_START);

        pnlButton.setBackground(new java.awt.Color(255, 255, 255));
        pnlButton.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(159, 32, 66))); // NOI18N
        pnlButton.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        btnADD.setBackground(new java.awt.Color(159, 32, 66));
        btnADD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnADD.setForeground(new java.awt.Color(255, 255, 255));
        btnADD.setText("Thêm");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });
        pnlButton.add(btnADD);

        btnUPDATE.setBackground(new java.awt.Color(159, 32, 66));
        btnUPDATE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUPDATE.setForeground(new java.awt.Color(255, 255, 255));
        btnUPDATE.setText("Sửa");
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });
        pnlButton.add(btnUPDATE);

        btnDELETE.setBackground(new java.awt.Color(159, 32, 66));
        btnDELETE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDELETE.setForeground(new java.awt.Color(255, 255, 255));
        btnDELETE.setText("Xóa");
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });
        pnlButton.add(btnDELETE);

        btnREFRESH.setBackground(new java.awt.Color(159, 32, 66));
        btnREFRESH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnREFRESH.setForeground(new java.awt.Color(255, 255, 255));
        btnREFRESH.setText("Refresh");
        btnREFRESH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREFRESHActionPerformed(evt);
            }
        });
        pnlButton.add(btnREFRESH);

        pnlFunction.add(pnlButton, java.awt.BorderLayout.CENTER);

        pnlDetails.add(pnlFunction, java.awt.BorderLayout.PAGE_END);

        Table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.setRowHeight(30);
        Table.setSelectionBackground(new java.awt.Color(159, 32, 66));
        Table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Table.getTableHeader().setReorderingAllowed(false);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        int row = Table.getSelectedRow();
        if (row != -1) {
            txtID.setText(String.valueOf(dt.getValueAt(row, 0)));
            txtName.setText(String.valueOf(dt.getValueAt(row, 1)));
            txtPrice.setText(String.valueOf(dt.getValueAt(row, 2)));
            cbxType.setSelectedItem(String.valueOf(dt.getValueAt(row, 3)));
            txtID.setEditable(false);
        }
    }//GEN-LAST:event_TableMouseClicked

    private void cbxSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSortActionPerformed
        int sort = cbxSort.getSelectedIndex();

        if (sort == 0) {
            setTableData(busSP.getAllSP());
        } else {
            setTableData(busSP.searchSP(String.valueOf(sort), 3));
        }
    }//GEN-LAST:event_cbxSortActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        try {
            txtID.setEditable(true);
            check();

            SanPham sp = setSP();
            busSP.addSP(sp);

            JOptionPane.showMessageDialog(this, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            Reset();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnADDActionPerformed

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        try {
            int row = Table.getSelectedRow();
            if (row == -1) {
                throw new Exception("Vui lòng chọn sản phẩm cần sửa");
            }
            check();

            SanPham sp = setSP();
            busSP.updateSP(sp);

            JOptionPane.showMessageDialog(this, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            Reset();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed
        try {
            int row = Table.getSelectedRow();
            if (row == -1) {
                throw new Exception("Vui lòng chọn sản phẩm cần xóa");
            }

            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?");

            if (confirm == JOptionPane.YES_OPTION) {
                busSP.deleteCTHD(txtID.getText());
                busSP.deleteSP(txtID.getText());

                JOptionPane.showMessageDialog(this, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                Reset();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDELETEActionPerformed

    private void btnREFRESHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREFRESHActionPerformed
        Reset();
    }//GEN-LAST:event_btnREFRESHActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            if (txtSearch.getText().trim().isEmpty()) {
                throw new Exception("Dữ liệu nhập trống");
            }
            int search = cbxSearch.getSelectedIndex();
            setTableData(busSP.searchSP(txtSearch.getText().trim(), search));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnREFRESH;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.JComboBox<String> cbxSearch;
    private javax.swing.JComboBox<String> cbxSort;
    private javax.swing.JComboBox<String> cbxType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lnlName;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlDetail;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlFunction;
    private javax.swing.JPanel pnlS;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JPanel pnlSort;
    private javax.swing.JPanel pnlText;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
